"""empty message

Revision ID: 620d4d036981
Revises: ce175811768d
Create Date: 2022-03-21 21:28:39.966845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620d4d036981'
down_revision = 'ce175811768d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logsubmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_delta', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=128), nullable=True),
    sa.Column('challenge', sa.String(length=128), nullable=True),
    sa.Column('ip_open', sa.String(length=32), nullable=True),
    sa.Column('date_open', sa.DateTime(), nullable=True),
    sa.Column('user_open', sa.String(length=128), nullable=True),
    sa.Column('ip_submit', sa.String(length=32), nullable=True),
    sa.Column('date_submit', sa.DateTime(), nullable=True),
    sa.Column('user_submit', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logsubmission')
    # ### end Alembic commands ###
