"""Add table for fb messages

Revision ID: 961147eac954
Revises: 6012fe8de495
Create Date: 2021-02-24 10:55:52.938388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961147eac954'
down_revision = '6012fe8de495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
