"""Add base anticheat

Revision ID: ce175811768d
Revises: 961147eac954
Create Date: 2022-03-09 08:08:47.215611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce175811768d'
down_revision = '961147eac954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anticheatevents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anticheatflags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('generation_time', sa.DateTime(), nullable=True),
    sa.Column('solve_time', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_hash', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('challenges', sa.Column('challenge_token', sa.String(length=80), nullable=True))
    op.add_column('challenges', sa.Column('file_hash', sa.String(length=32), nullable=True))
    op.add_column('files', sa.Column('participant', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'participant')
    op.drop_column('challenges', 'file_hash')
    op.drop_column('challenges', 'challenge_token')
    op.drop_table('anticheatflags')
    op.drop_table('anticheatevents')
    # ### end Alembic commands ###
